version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      - MONGO_URI=mongodb://database:27017
    links:
        - database
  
  database:
    image: mongo:latest
    hostname: notes_mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=notes
      - MONGO_INITDB_ROOT_USERNAME=hannora
      - MONGO_INITDB_ROOT_PASSWORD=hannora123