name: CI/CD Pipeline

on:
  push:
    branches: 
      - main
    # paths: 
    #   - backend/**
  
# allows you to manually execute this pipeline from the Actions tab.
# workflow_dispatch:


defaults:
 run:
  working-directory: ./backend

jobs:
  build-flask-app:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10' 

    - run: pip install -r requirements.txt  # install requirements to enable GitHub run tests
    
    - run:  python test_app.py
      # working-directory: ./backend/tests

