name: CI/CD Pipeline

on:
  push:
    branches: 
      - main
    # paths: 
    #   - backend/**
  
# allows you to manually execute this pipeline from the Actions tab.
# workflow_dispatch:


defaults:
 run:
  working-directory: ./backend

jobs:
  app-unit-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code 
      uses: actions/checkout@v4

    - name: Setup Python 
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
    
    - name: Create virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Print debugging information 
      run: |
        echo "Python Version: $(python --version)"
        echo "Working Directory: $(pwd)"
        echo "Contents of Working Directory: $(ls -l)"
        echo "Contents of site-packages: $(ls -l venv/lib/python*/site-packages)"
        
    - name: App Unittests
      run:  python test_app.py


  app-sonarcloud-scan:
    needs: app-unit-test
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code 
        uses: actions/checkout@v4
         

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v3
        with:
          path: ~/.sonar/sonar-scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: |
            ${{ runner.os }}-sonar-scanner

      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        run: |
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip sonar-scanner.zip -d ~/.sonar/
          mv ~/.sonar/sonar-scanner-* ~/.sonar/sonar-scanner
          echo "SONAR_SCANNER_HOME=~/.sonar/sonar-scanner" >> $GITHUB_ENV

      - name: Add SonarCloud scanner to PATH
        run: echo "$SONAR_SCANNER_HOME/bin" >> $GITHUB_PATH

      - name: Run SonarCloud scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
          -Dsonar.projectKey=my_project_key \
          -Dsonar.organization=my_organization_key \
          -Dsonar.sources=. \
          -Dsonar.projectVersion=1.0 \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
  publish-app:
    needs: app-sonarcloud-scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code 
      uses: actions/checkout@v4

    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/notes:latest
